$ANSIBLE_VAULT;1.1;AES256
63393036633563633063613132316332316331623337336236376139626466636161353334633730
6339653961373033373262346435383466323962306637650a616264366336366432343262393666
62373561343262316435303462643664613539383561306438626332313062383363386431326131
3663333266626538610a313363656532323061303638323862356339323739323538343137383662
38303063623463666138356235353937646466666532393331656665313130366638643137666437
64316237643535366330346236633066326365303038366334663136373634663338383838316239
31663434333165326161333934373130306463336264383763343963313935666461343837313162
31653834323162646331613061653035383331386665366466636663626264363165393135623363
6633
